"""Real SMTP email sending (Phase 16f) — the piece that makes cash-and-carry
alerts genuinely autonomous, independent of Claude. Requires
`GMAIL_APP_PASSWORD`/`GMAIL_SENDER_ADDRESS` in the environment (a Gmail App
Password, generated by the user at myaccount.google.com/apppasswords --
this module never asks for or handles a real account password). Returns
"mock" (no send attempted) when those aren't configured, the same
mock-fallback convention used everywhere else in this codebase
(scaata.live.alpaca_broker, scaata.rl.llm_baseline) so a placeholder can
never be mistaken for a real send.

This is a real, standing capability: any caller with access to this
function can send email as the configured Gmail account. Only call it for
genuinely detected conditions (see scaata.notify.opportunity_alert), never
speculatively.
"""
from __future__ import annotations

import os
import smtplib
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def _credentials() -> tuple[str, str] | None:
    sender = os.environ.get("GMAIL_SENDER_ADDRESS")
    app_password = os.environ.get("GMAIL_APP_PASSWORD")
    if not sender or not app_password:
        return None
    return sender, app_password.replace(" ", "")  # Google displays it space-separated; SMTP auth needs it without


def send_email(to: str, subject: str, body: str) -> tuple[dict, str]:
    """Sends a real email via Gmail SMTP. Returns ({"to", "subject"}, source)
    -- source="mock" (no network call made) when credentials aren't
    configured, source="live" after an actual send.
    """
    creds = _credentials()
    if creds is None:
        return {"to": to, "subject": subject}, "mock"

    sender, app_password = creds
    message = MIMEText(body)
    message["Subject"] = subject
    message["From"] = sender
    message["To"] = to

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
        server.starttls()
        server.login(sender, app_password)
        server.sendmail(sender, [to], message.as_string())

    return {"to": to, "subject": subject}, "live"
